**Que01**

In [ ]:
import pandas as pd

# Load dataset
df = pd.read_csv("IMDB Dataset.csv",engine='python',on_bad_lines='skip')

df.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

Select 100 positive and 100 negative reviews.

In [ ]:
# Select 100 documents from different categories
docs = df.groupby("sentiment").head(100)   #  from each category (2 categories = 200 docs)
pos =df.groupby("sentiment").get_group("positive").head(100)
neg =df.groupby("sentiment").get_group("negative").head(100)

print(docs.head())
print(len(docs))
print(len(pos))
print(len(neg))

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive
200
100
100

In [ ]:
!pip install nltk
!pip install spacy

Requirement already satisfied: nltk in /usr/local/lib/python3.12/dist-packages (3.9.1)
Requirement already satisfied: click in /usr/local/lib/python3.12/dist-packages (from nltk) (8.3.1)
Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (from nltk) (1.5.3)
Requirement already satisfied: regex>=2021.8.3 in /usr/local/lib/python3.12/dist-packages (from nltk) (2025.11.3)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from nltk) (4.67.3)
Requirement already satisfied: spacy in /usr/local/lib/python3.12/dist-packages (3.8.11)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.4.0,>=8.3.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (8.3.10)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in /usr/local/lib/python3.12/dist-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.4.3)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (0.21.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (4.67.3)
Requirement already satisfied: numpy>=1.19.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.0.2)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.32.4)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in /usr/local/lib/python3.12/dist-packages (from spacy) (2.12.3)
Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from spacy) (75.2.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from spacy) (26.0)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<1.4.0,>=1.3.0 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (1.3.3)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in /usr/local/lib/python3.12/dist-packages (from thinc<8.4.0,>=8.3.4->spacy) (0.1.5)
Requirement already satisfied: click>=8.0.0 in /usr/local/lib/python3.12/dist-packages (from typer-slim<1.0.0,>=0.3.0->spacy) (8.3.1)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in /usr/local/lib/python3.12/dist-packages (from weasel<0.5.0,>=0.4.2->spacy) (7.5.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->spacy) (3.0.3)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.4.2->spacy) (2.1.1)

In [ ]:
import nltk
import spacy

nltk.download('punkt')
nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('averaged_perceptron_tagger')
nltk.download('averaged_perceptron_tagger_eng')
nltk.download('wordnet')

nlp = spacy.load("en_core_web_sm")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger.zip.
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     /root/nltk_data...
[nltk_data]   Unzipping taggers/averaged_perceptron_tagger_eng.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...

2. Perform complete preprocessing
pipeline.

In [ ]:
# Converting to list for preprocessing
documents = docs['review'].tolist()
pos_documents = pos['review'].tolist()
neg_documents = neg['review'].tolist()
print(len(documents))
print(len(pos_documents))
print(len(neg_documents))

200
100
100

In [ ]:
# Preprocess


import nltk
import spacy
from nltk.tokenize import sent_tokenize, word_tokenize
from nltk.corpus import stopwords
from nltk.stem import PorterStemmer, WordNetLemmatizer

nlp = spacy.load("en_core_web_sm")

stop_words = set(stopwords.words('english'))
ps = PorterStemmer()
lemmatizer = WordNetLemmatizer()

results = []

for doc_text in documents:

    # Sentence Segmentation
    sentences = sent_tokenize(doc_text)

    # Tokenization
    tokens = word_tokenize(doc_text)

    # Stopword Removal
    filtered = [w for w in tokens if w.lower() not in stop_words and w.isalpha()]

    # Stemming
    stemmed = [ps.stem(w) for w in filtered]

    # Lemmatization
    lemmatized = [lemmatizer.lemmatize(w) for w in filtered]

    results.append({
        "sentences": sentences,
        "tokens": tokens,
        "filtered": filtered,
        "stemmed": stemmed,
        "lemmatized": lemmatized
    })

print("Processed all 20 documents successfully!")
print(len(results))

Result = pd.DataFrame(results)
Result

Processed all 20 documents successfully!
200

,sentences,tokens,filtered,stemmed,lemmatized
0,[One of the other reviewers has mentioned that...,"[One, of, the, other, reviewers, has, mentione...","[One, reviewers, mentioned, watching, Oz, epis...","[one, review, mention, watch, oz, episod, hook...","[One, reviewer, mentioned, watching, Oz, episo..."
1,"[A wonderful little production., <br /><br />T...","[A, wonderful, little, production, ., <, br, /...","[wonderful, little, production, br, br, filmin...","[wonder, littl, product, br, br, film, techniq...","[wonderful, little, production, br, br, filmin..."
2,[I thought this was a wonderful way to spend t...,"[I, thought, this, was, a, wonderful, way, to,...","[thought, wonderful, way, spend, time, hot, su...","[thought, wonder, way, spend, time, hot, summe...","[thought, wonderful, way, spend, time, hot, su..."
3,[Basically there's a family where a little boy...,"[Basically, there, 's, a, family, where, a, li...","[Basically, family, little, boy, Jake, thinks,...","[basic, famili, littl, boy, jake, think, zombi...","[Basically, family, little, boy, Jake, think, ..."
4,"[Petter Mattei's ""Love in the Time of Money"" i...","[Petter, Mattei, 's, ``, Love, in, the, Time, ...","[Petter, Mattei, Love, Time, Money, visually, ...","[petter, mattei, love, time, money, visual, st...","[Petter, Mattei, Love, Time, Money, visually, ..."
...,...,...,...,...,...
195,"[I think this movie has got it all., It has re...","[I, think, this, movie, has, got, it, all, ., ...","[think, movie, got, really, cool, music, never...","[think, movi, got, realli, cool, music, never,...","[think, movie, got, really, cool, music, never..."
196,[Howard (Kevin Kline) teaches English at the h...,"[Howard, (, Kevin, Kline, ), teaches, English,...","[Howard, Kevin, Kline, teaches, English, high,...","[howard, kevin, kline, teach, english, high, s...","[Howard, Kevin, Kline, teach, English, high, s..."
197,[We usually think of the British as the expert...,"[We, usually, think, of, the, British, as, the...","[usually, think, British, experts, rendering, ...","[usual, think, british, expert, render, great,...","[usually, think, British, expert, rendering, g..."
198,[One of Starewicz's longest and strangest shor...,"[One, of, Starewicz, 's, longest, and, strange...","[One, Starewicz, longest, strangest, short, fi...","[one, starewicz, longest, strangest, short, fi...","[One, Starewicz, longest, strangest, short, fi..."
199,[Nice character development in a pretty cool m...,"[Nice, character, development, in, a, pretty, ...","[Nice, character, development, pretty, cool, m...","[nice, charact, develop, pretti, cool, milieu,...","[Nice, character, development, pretty, cool, m..."

3. Compare:
* Stemmed vs Lemmatized
* vocabulary size.

In [ ]:
import pandas as pd

all_original = []
all_stemmed = []
all_lemmatized = []

for r in results:
    all_original.extend(r["filtered"])
    all_stemmed.extend(r["stemmed"])
    all_lemmatized.extend(r["lemmatized"])

comparison_df = pd.DataFrame({
    "Original": all_original,
    "Stemmed": all_stemmed,
    "Lemmatized": all_lemmatized
})

print(comparison_df.head(30))

       Original   Stemmed   Lemmatized
0           One       one          One
1     reviewers    review     reviewer
2     mentioned   mention    mentioned
3      watching     watch     watching
4            Oz        oz           Oz
5       episode    episod      episode
6        hooked      hook       hooked
7         right     right        right
8       exactly   exactli      exactly
9      happened    happen     happened
10           br        br           br
11           br        br           br
12        first     first        first
13        thing     thing        thing
14       struck    struck       struck
15           Oz        oz           Oz
16    brutality    brutal    brutality
17  unflinching  unflinch  unflinching
18       scenes     scene        scene
19     violence   violenc     violence
20          set       set          set
21        right     right        right
22         word      word         word
23           GO        go           GO
24        Trust     trust        Trust
25         show      show         show
26        faint     faint        faint
27      hearted     heart      hearted
28        timid     timid        timid
29         show      show         show

Perform POS tagging using:

*  NLTK
* spaCy

In [ ]:
# nltk
all_nltk_pos = []

for r in results:
    pos_tags = nltk.pos_tag(r["filtered"])
    all_nltk_pos.extend(pos_tags)


nltk_pos = pd.DataFrame(all_nltk_pos, columns=["Word", "POS"])
print("NLTK POS tagging")
print(nltk_pos.head(20))
print(f"\n\n\n\n")

#Spacy

all_spacy_pos = []

for doc_text in documents:
    doc = nlp(doc_text)
    spacy_tags = [(token.text, token.pos_) for token in doc]
    all_spacy_pos.extend(spacy_tags)

nltk_pos = pd.DataFrame(all_nltk_pos, columns=["Word", "POS"])
print("Spacy POS tagging")
print(nltk_pos.head(20))

NLTK POS tagging
           Word  POS
0           One   CD
1     reviewers  NNS
2     mentioned  VBD
3      watching  VBG
4            Oz  NNP
5       episode   NN
6        hooked  VBD
7         right   RB
8       exactly   RB
9      happened  VBN
10           br   NN
11           br   NN
12        first   JJ
13        thing   NN
14       struck  VBD
15           Oz  NNP
16    brutality   NN
17  unflinching  VBG
18       scenes  NNS
19     violence   NN





Spacy POS tagging
           Word  POS
0           One   CD
1     reviewers  NNS
2     mentioned  VBD
3      watching  VBG
4            Oz  NNP
5       episode   NN
6        hooked  VBD
7         right   RB
8       exactly   RB
9      happened  VBN
10           br   NN
11           br   NN
12        first   JJ
13        thing   NN
14       struck  VBD
15           Oz  NNP
16    brutality   NN
17  unflinching  VBG
18       scenes  NNS
19     violence   NN

**NER**

In [ ]:
# NER

all_entities = []

for doc_text in documents:
    doc = nlp(doc_text)
    for ent in doc.ents:
        all_entities.append((ent.text, ent.label_))

print(f"All the entities:\n{all_entities[:10]}\n")

All the entities:
[('One', 'CARDINAL'), ('1', 'CARDINAL'), ('GO', 'ORG'), ('OZ', 'ORG'), ('the Oswald Maximum Security State Penitentary', 'ORG'), ('Emerald City', 'GPE'), ('Em City', 'GPE'), ('Aryans', 'NORP'), ('Muslims', 'NORP'), ('Latinos', 'ORG')]

**6**. Identify

In [ ]:
import nltk
from nltk.corpus import wordnet as wn
from nltk.tokenize import word_tokenize
import string

nltk.download('punkt')
nltk.download('wordnet')

# Combine all text
all_text = " ".join(docs['review'].astype(str))

# Tokenize
tokens = word_tokenize(all_text.lower())

# Remove punctuation
tokens = [w for w in tokens if w.isalpha()]

# Unique words only
unique_words = list(set(tokens))

# Find ambiguous words (more than 1 synset)
ambiguous_words = []

for word in unique_words:
    synsets = wn.synsets(word)
    if len(synsets) > 1:
        ambiguous_words.append((word, len(synsets)))

# Sort by number of meanings
ambiguous_words = sorted(ambiguous_words, key=lambda x: x[1], reverse=True)

# Show top 10 most ambiguous words
print("Top ambiguous words found in your dataset:\n")
for word, count in ambiguous_words[:10]:
    print(word, "->", count, "meanings")

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!

Top ambiguous words found in your dataset:

break -> 75 meanings
breaks -> 75 meanings
broken -> 72 meanings
cut -> 70 meanings
cuts -> 61 meanings
breaking -> 60 meanings
broke -> 60 meanings
run -> 57 meanings
runs -> 57 meanings
made -> 52 meanings

In [ ]:
word = ambiguous_words[0][0]  # Most ambiguous word
synsets = wn.synsets(word)

print(f"\nSelected Word: {word}\n")

for i, syn in enumerate(synsets[:2]):  # Show first 2 meanings
    print(f"Meaning {i+1}:")
    print("Definition:", syn.definition())
    print("Example:", syn.examples())
    print()

Selected Word: break

Meaning 1:
Definition: some abrupt occurrence that interrupts an ongoing activity
Example: ['the telephone is an annoying interruption', 'there was a break in the action when a player was hurt']

Meaning 2:
Definition: an unexpected piece of good luck
Example: ['he finally got his big break']

In [ ]:
import nltk
from nltk import CFG
from nltk.parse import ChartParser

grammar = CFG.fromstring("""
S -> NP VP
NP -> Det N | NP PP | 'I'
VP -> V NP | VP PP
PP -> P NP
Det -> 'the' | 'a'
N -> 'man' | 'telescope'
V -> 'saw'
P -> 'with'
""")

parser = ChartParser(grammar)

sentence = "I saw the man with a telescope".split()

for tree in parser.parse(sentence):
    print(tree)
    tree.pretty_print()

(S
  (NP I)
  (VP
    (VP (V saw) (NP (Det the) (N man)))
    (PP (P with) (NP (Det a) (N telescope)))))
     S
  ___|___________
 |               VP
 |        _______|________
 |       VP               PP
 |    ___|___         ____|___
 |   |       NP      |        NP
 |   |    ___|___    |     ___|______
 NP  V  Det      N   P   Det         N
 |   |   |       |   |    |          |
 I  saw the     man with  a      telescope

(S
  (NP I)
  (VP
    (V saw)
    (NP
      (NP (Det the) (N man))
      (PP (P with) (NP (Det a) (N telescope))))))
     S
  ___|___________
 |               VP
 |    ___________|___
 |   |               NP
 |   |        _______|____
 |   |       |            PP
 |   |       |        ____|___
 |   |       NP      |        NP
 |   |    ___|___    |     ___|______
 NP  V  Det      N   P   Det         N
 |   |   |       |   |    |          |
 I  saw the     man with  a      telescope

**Que** 2
 (Document Representation +
Similarity + Embeddings)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TfidfVectorizer
tfidf_vectorizer = TfidfVectorizer()

vectorizer = TfidfVectorizer(
    stop_words='english',
    max_features=1000
)

tfidf_matrix = vectorizer.fit_transform(documents)
pos_tfidf_matrix = vectorizer.transform(pos_documents)
neg_tfidf_matrix = vectorizer.transform(neg_documents)

print("TF-IDF Shape:", tfidf_matrix.shape)

feature_names = vectorizer.get_feature_names_out()

tfidf_df = pd.DataFrame(
    tfidf_matrix.toarray(),
    columns=feature_names
)

print(tfidf_df.head())

TF-IDF Shape: (200, 1000)
        10  1984   20   23  ability  able  absolutely  accent  accepted  \
0  0.00000   0.0  0.0  0.0      0.0   0.0         0.0     0.0       0.0
1  0.00000   0.0  0.0  0.0      0.0   0.0         0.0     0.0       0.0
2  0.00000   0.0  0.0  0.0      0.0   0.0         0.0     0.0       0.0
3  0.09229   0.0  0.0  0.0      0.0   0.0         0.0     0.0       0.0
4  0.00000   0.0  0.0  0.0      0.0   0.0         0.0     0.0       0.0

   according  ...  writing   written  wrong  year     years  yes      york  \
0        0.0  ...      0.0  0.000000    0.0   0.0  0.000000  0.0  0.000000
1        0.0  ...      0.0  0.148345    0.0   0.0  0.000000  0.0  0.000000
2        0.0  ...      0.0  0.000000    0.0   0.0  0.126426  0.0  0.000000
3        0.0  ...      0.0  0.000000    0.0   0.0  0.000000  0.0  0.000000
4        0.0  ...      0.0  0.000000    0.0   0.0  0.000000  0.0  0.130999

      young    zombie  zombies
0  0.000000  0.000000      0.0
1  0.000000  0.000000      0.0
2  0.131666  0.000000      0.0
3  0.000000  0.342269      0.0
4  0.000000  0.000000      0.0

[5 rows x 1000 columns]

TOP 10 pos & neg

In [ ]:
import numpy as np

# Average TF-IDF score for positive reviews
pos_mean = np.mean(pos_tfidf_matrix.toarray(), axis=0)

# Average TF-IDF score for negative reviews
neg_mean = np.mean(neg_tfidf_matrix.toarray(), axis=0)

# Get top 10 indices
top_pos_indices = pos_mean.argsort()[-10:][::-1]
top_neg_indices = neg_mean.argsort()[-10:][::-1]

print("Top 10 Positive Words:")
for idx in top_pos_indices:
    print(feature_names[idx], ":", pos_mean[idx])

print("\nTop 10 Negative Words:")
for idx in top_neg_indices:
    print(feature_names[idx], ":", neg_mean[idx])

Top 10 Positive Words:
br : 0.1413880741450509
film : 0.06897033265601654
movie : 0.06425452832564775
like : 0.03152019969741204
really : 0.029084356708895146
way : 0.027885057107204247
great : 0.0276077385994122
old : 0.0271852146877176
time : 0.02702198063847704
little : 0.02572419090268634

Top 10 Negative Words:
br : 0.16807415022378921
movie : 0.0947445581027756
film : 0.07495965953942453
just : 0.05232425825581715
like : 0.044028107989797526
bad : 0.0419175840795773
good : 0.03359765339363584
movies : 0.031831360953687014
don : 0.02885697921319251
story : 0.027546080148865136

2.Cosine similarity

*   two positve reviews
*   two negative reviews

In [ ]:
from sklearn.metrics.pairwise import cosine_similarity

# Take first two positive reviews
pos_vec1 = pos_tfidf_matrix[0]
pos_vec2 = pos_tfidf_matrix[1]

# Compute cosine similarity
similarity_pos_pos = cosine_similarity(pos_vec1, pos_vec2)

print("Cosine Similarity (Positive vs Positive):", similarity_pos_pos[0][0])

# Taking one neg and one pos
pos_vec = pos_tfidf_matrix[0]
neg_vec = neg_tfidf_matrix[0]

similarity_pos_neg = cosine_similarity(pos_vec, neg_vec)

print("Cosine Similarity (Positive vs Negative):", similarity_pos_neg[0][0])

Cosine Similarity (Positive vs Positive): 0.0871186189598691
Cosine Similarity (Positive vs Negative): 0.0722438376036933

3. Use GloVe embeddings:
* Find similarity between:
“good” and “excellent”
“good” and “bad”
* Find top-5 similar words to
“terrible”

In [ ]:
!pip install gensim
import gensim.downloader as api

# This will download automatically first time
glove = api.load("glove-wiki-gigaword-100")

print("Model loaded successfully!")

Collecting gensim
  Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (8.4 kB)
Requirement already satisfied: numpy>=1.18.5 in /usr/local/lib/python3.12/dist-packages (from gensim) (2.0.2)
Requirement already satisfied: scipy>=1.7.0 in /usr/local/lib/python3.12/dist-packages (from gensim) (1.16.3)
Requirement already satisfied: smart_open>=1.8.1 in /usr/local/lib/python3.12/dist-packages (from gensim) (7.5.0)
Requirement already satisfied: wrapt in /usr/local/lib/python3.12/dist-packages (from smart_open>=1.8.1->gensim) (2.1.1)
Downloading gensim-4.4.0-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (27.9 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 44.6 MB/s eta 0:00:00
Installing collected packages: gensim
Successfully installed gensim-4.4.0
[==================================================] 100.0% 128.1/128.1MB downloaded
Model loaded successfully!

In [ ]:
print("good vs excellent:", glove.similarity("good", "excellent"))
print("good vs bad:", glove.similarity("good", "bad"))
print(glove.most_similar("terrible", topn=5))

good vs excellent: 0.7936238
good vs bad: 0.7702798
[('horrible', 0.9194772243499756), ('awful', 0.8742169737815857), ('dreadful', 0.7821513414382935), ('horrendous', 0.7782431840896606), ('horrific', 0.7643980979919434)]

 **Que** 3 (Classification + Error Analysis)
1. Split data 80–20.
2. Train:
* Naïve Bayes
* Logistic Regression
3. Compare metrics.
4. Show confusion matrix.
5. Perform error analysis:
* Print 5 misclassified reviews
* Explain possible reason.

In [ ]:
docs.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

x = docs['review']
y = docs['sentiment']



le = LabelEncoder()
y = le.fit_transform(docs['sentiment'])


X_train, X_test, y_train, y_test = train_test_split(
    x,
    y,
    test_size=0.2,
    random_state=42,)

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer


vectorizer = TfidfVectorizer(stop_words='english', max_df=0.7)

X_test_text = X_test
# Applying Tfid to train and test
X_train = vectorizer.fit_transform(X_train)
y_train = y_train

X_test = vectorizer.transform(X_test)
y_test = y_test

In [ ]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, precision_score, recall_score,f1_score,classification_report



nb = MultinomialNB()
nb.fit(X_train, y_train)

nb_pred = nb.predict(X_test)

print(classification_report(y_test,nb_pred))


nb_accuracy = accuracy_score(y_test, nb_pred)
nb_precision = precision_score(y_test, nb_pred, average='weighted')
nb_recall = recall_score(y_test, nb_pred, average='weighted')
nb_f1 = f1_score(y_test, nb_pred, average='weighted')

              precision    recall  f1-score   support

           0       0.74      0.77      0.76        22
           1       0.71      0.67      0.69        18

    accuracy                           0.72        40
   macro avg       0.72      0.72      0.72        40
weighted avg       0.72      0.72      0.72        40

In [ ]:
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)

lr_pred = lr.predict(X_test)

print(accuracy_score(y_test, lr_pred))
print(classification_report(y_test,lr_pred))


lr_accuracy = accuracy_score(y_test, lr_pred)
lr_precision = precision_score(y_test, lr_pred, average='weighted')
lr_recall = recall_score(y_test, lr_pred, average='weighted')
lr_f1 = f1_score(y_test, lr_pred, average='weighted')

0.575
              precision    recall  f1-score   support

           0       0.67      0.45      0.54        22
           1       0.52      0.72      0.60        18

    accuracy                           0.57        40
   macro avg       0.59      0.59      0.57        40
weighted avg       0.60      0.57      0.57        40

In [ ]:
Comparison_table = pd.DataFrame({
    'Model': ['Naive Bayes', 'Logistic Regression'],
    'Accuracy': [nb_accuracy, lr_accuracy],
    'Precision': [nb_precision, lr_accuracy],
    'Recall': [nb_recall, lr_recall],
    'F1 Score': [nb_f1, lr_f1]
})

print(Comparison_table)

                 Model  Accuracy  Precision  Recall  F1 Score
0          Naive Bayes     0.725   0.724169   0.725  0.724127
1  Logistic Regression     0.575   0.575000   0.575  0.569390

In [ ]:
import numpy as np

misclassified = np.where(lr_pred != y_test)[0]

print("Total misclassified:", len(misclassified))


for i in misclassified[:5]:
    print("Review:")
    print(X_test_text.iloc[i])   # Now this works

    print("Actual:", le.inverse_transform([y_test[i]])[0])
    print("Predicted:", le.inverse_transform([lr_pred[i]])[0])

    print("-" * 80)

Total misclassified: 17
Review:
Kind of drawn in by the erotic scenes, only to realize this was one of the most amateurish and unbelievable bits of film I've ever seen. Sort of like a high school film project. What was Rosanna Arquette thinking?? And what was with all those stock characters in that bizarre supposed Midwest town? Pretty hard to get involved with this one. No lessons to be learned from it, no brilliant insights, just stilted and quite ridiculous (but lots of skin, if that intrigues you) videotaped nonsense....What was with the bisexual relationship, out of nowhere, after all the heterosexual encounters. And what was with that absurd dance, with everybody playing their stereotyped roles? Give this one a pass, it's like a million other miles of bad, wasted film, money that could have been spent on starving children or Aids in Africa.....
Actual: negative
Predicted: positive
--------------------------------------------------------------------------------
Review:
The story is very trustworthy and powerful. The technical side of the movie is quite fine.. even the directing of it. The main problem is with the castings, that turned that movie into almost another local and regular cliché with a great lack of impact and even greater lack of impression. Beside the small role of the father, Rafael (played impressively by Asi Dayan), all other actors were unfortunately not in their best. The role of the elder Blind girl, played by Taly Sharon, was fresh but without any intensity as the leading role. therefore the figure she acted had become mild and low profile. There were moments and episodes that looked more like a rehearsal then a real movie. But after all it's a good point to begin from and to make big improvements in the future.
Actual: negative
Predicted: positive
--------------------------------------------------------------------------------
Review:
This movie was one of the best movies that I have seen this year. I didn't see any cameos in the movie, but it is still pretty good. It is similar to Anchorman in the humor department, but I think this is a better put together movie. It actually has a point. If you are going to see a whole bunch of T&A you will be disappointed. Just a well put together movie!!!! If you have nothing to do for the day or you need a lot of humor, you will find this to be a really good movie. I definitely think that Ebert and Roeper's review of this movie is right on. I mean, I don't really like Ebert on most movies, but this is the movie that I will agree about. The movie contains a good enough story that it is actually believable that these type of people are out there. There is definitely something to be said about how they treat virginity in this movie. Yea, sure, you get laughed at when it is found out about, but it still suggests that you wait. Steve did a wonderful job of portraying the person that he did in this movie and yet, it is still funny.
Actual: positive
Predicted: negative
--------------------------------------------------------------------------------
Review:
This film laboured along with some of the most predictable story lines and shallow characters ever seen. The writer obviously bought the playbook "How to write a space disaster movie" and followed it play by play. In particular, the stereo-typical use of astronauts talking to their loved ones from outer space - putting on a brave show in the face of disaster - has been done time and time again.<br /><br />Max Q appears to have been written in the hope that the producers would throw $50 million at the project. But, judging by the latter half of the film which contained numerous lame attempts at special effects, the producers could only muster $50 thousand. To learn that the film was nominated for a "Special Visual Effects" Emmy has me absolutely gob-smacked.<br /><br />I think a handful of high school students with a pass in Media Studies could have created more believable effects!<br /><br />And the plot holes are too numerous to mention. But I will pick one out as an example. Now, I'm no NASA expert, but surely it's highly implausible that a worker attached to the shuttle simulator would suddenly hold a position of power in the control room when things start to go pear-shaped with the program. Surely there is someone more experienced at Mission Control who the Program Director would call on rather than a twenty-nine year old who has not been in the control room before.<br /><br />The only saving grace for this film is the work of Bill Campbell. He manages to make a good attempt at salvaging something out of the train wreck that is this script.<br /><br />I give this film 2 out of 10, with the above-average work of Bill Campbell in the lead role saving it from a lower mark.
Actual: negative
Predicted: positive
--------------------------------------------------------------------------------
Review:
As a disclaimer, I've seen the movie 5-6 times in the last 15 years, and I only just saw the musical this week. This allowed me to judge the movie without being tainted by what was or wasn't in the musical (however, it tainted me when I watched the musical :) ) <br /><br />I actually believe Michael Douglas worked quite well in that role, along with Kasey. I think her 'Let me dance for you scene' is one of the best parts of the movie, a worthwhile addition compared to the musical. The dancers and singing in the movie are much superior to the musical, as well as the cast which is at least 10 times bigger (easier to do in the movie of course). The decors, lighting, dancing, and singing are also much superior in the movie, which should be expected, and was indeed delivered. <br /><br />The songs that were in common with the musical are better done in the movie, the new ones are quite good ones, and the whole movie just delivers more than the musical in my opinion, especially compared to a musical which has few decors. The one bad point on the movie is the obvious cuts between the actors talking, and dubbed singers during the singing portions for some of the characters, but their dancing is impeccable, and the end product was more enjoyable than the musical
Actual: positive
Predicted: negative
--------------------------------------------------------------------------------